[build]
  # Since this is a static HTML site, no build command is needed
  # Netlify will serve the files directly
  command = ""
  publish = "."

[[headers]]
  # Enable CORS for all files
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  # Redirect root to index.html
  from = "/"
  to = "/index.html"
  status = 200

# Optional: Enable form processing if you add forms later
[build.environment]
  NODE_VERSION = "18"

# Explicitly disable framework detection
[build.processing]
  skip_processing = false

# Ensure this is treated as a static site
[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true
