# Netlify configuration for static HTML site
[build]
  # No build command needed for static HTML
  command = ""
  # Publish the current directory (where index.html is located)
  publish = "."
  # Base directory is the root
  base = "."

# Headers for CORS and security
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Redirects for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Processing settings for static files
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true